#!/usr/bin/env node
/**
 * Build script to concatenate modular CSS files into globals.css
 * This avoids @import issues with Next.js/Turbopack
 */

const fs = require('fs');
const path = require('path');

const cssModules = [
  // Base
  'base/reset.css',
  'base/typography.css',
  'base/cursor.css',
  
  // Components
  'components/loader.css',
  'components/navigation.css',
  'components/modal.css',
  
  // Sections
  'sections/awards.css',
  'sections/hero.css',
  'sections/statement.css',
  'sections/services.css',
  'sections/works.css',
  'sections/marquee.css',
  'sections/about.css',
  'sections/process.css',
  'sections/contact.css',
  
  // Responsive
  'responsive/touch.css',
  'responsive/tablet.css',
];

const header = `/* ═══════════════════════════════════════════════════════════
   LUMIÈRE - COMPILED CSS
   
   This file is auto-generated from modular CSS files in src/css/
   To edit styles, modify files in src/css/ and run: node build-css.js
   
   DO NOT EDIT THIS FILE DIRECTLY
   ═══════════════════════════════════════════════════════════ */

`;

let output = header;

console.log('🎨 Building CSS from modules...\n');

for (const module of cssModules) {
  const filePath = path.join('src/css', module);
  
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    output += `\n/* ────────────────────────────────────────────────────────────\n   FROM: ${module}\n   ──────────────────────────────────────────────────────────── */\n\n`;
    output += content + '\n';
    console.log(`✓ ${module}`);
  } else {
    console.warn(`⚠ Missing: ${module}`);
  }
}

fs.writeFileSync('src/app/globals.css', output, 'utf8');

console.log('\n✅ CSS build complete! Output: src/app/globals.css');
console.log(`📊 Total size: ${(output.length / 1024).toFixed(2)} KB`);
