/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/bulbs.glb -o src/components/BulbsModel.tsx 
Author: Nicholas-3D (https://sketchfab.com/Nicholas01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/decorative-hanging-light-bulbs-set-free-a640603e356340ab82e52a62a12c00aa
Title: Decorative Hanging Light Bulbs Set Free
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bulb_B004_M_BulbGlass_0: THREE.Mesh
    Bulb_B004_M_BulbHolder_0: THREE.Mesh
    Bulb_B004_M_BulbFilament_0: THREE.Mesh
    Bulb_A004_M_BulbGlass_0: THREE.Mesh
    Bulb_A004_M_BulbHolder_0: THREE.Mesh
    Bulb_A004_M_BulbFilament_0: THREE.Mesh
    Bulb_C003_M_BulbGlass_0: THREE.Mesh
    Bulb_C003_M_BulbHolder_0: THREE.Mesh
    Bulb_C003_M_BulbFilament_0: THREE.Mesh
    Bulb_D005_M_BulbGlass_0: THREE.Mesh
    Bulb_D005_M_BulbHolder_0: THREE.Mesh
    Bulb_D005_M_BulbFilament_0: THREE.Mesh
    Bulb_E005_M_BulbGlass_0: THREE.Mesh
    Bulb_E005_M_BulbHolder_0: THREE.Mesh
    Bulb_E005_M_BulbFilament_0: THREE.Mesh
    Bulb_B001_M_BulbGlass_0: THREE.Mesh
    Bulb_B001_M_BulbHolder_0: THREE.Mesh
    Bulb_B001_M_BulbFilament_0: THREE.Mesh
    Bulb_A001_M_BulbGlass_0: THREE.Mesh
    Bulb_A001_M_BulbHolder_0: THREE.Mesh
    Bulb_A001_M_BulbFilament_0: THREE.Mesh
    Bulb_C001_M_BulbGlass_0: THREE.Mesh
    Bulb_C001_M_BulbHolder_0: THREE.Mesh
    Bulb_C001_M_BulbFilament_0: THREE.Mesh
    Bulb_D001_M_BulbGlass_0: THREE.Mesh
    Bulb_D001_M_BulbHolder_0: THREE.Mesh
    Bulb_D001_M_BulbFilament_0: THREE.Mesh
    Bulb_E001_M_BulbGlass_0: THREE.Mesh
    Bulb_E001_M_BulbHolder_0: THREE.Mesh
    Bulb_E001_M_BulbFilament_0: THREE.Mesh
    Bulb_B002_M_BulbGlass_0: THREE.Mesh
    Bulb_B002_M_BulbHolder_0: THREE.Mesh
    Bulb_B002_M_BulbFilament_0: THREE.Mesh
    Bulb_A002_M_BulbGlass_0: THREE.Mesh
    Bulb_A002_M_BulbHolder_0: THREE.Mesh
    Bulb_A002_M_BulbFilament_0: THREE.Mesh
    Bulb_C002_M_BulbGlass_0: THREE.Mesh
    Bulb_C002_M_BulbHolder_0: THREE.Mesh
    Bulb_C002_M_BulbFilament_0: THREE.Mesh
    Bulb_D002_M_BulbGlass_0: THREE.Mesh
    Bulb_D002_M_BulbHolder_0: THREE.Mesh
    Bulb_D002_M_BulbFilament_0: THREE.Mesh
    Bulb_E002_M_BulbGlass_0: THREE.Mesh
    Bulb_E002_M_BulbHolder_0: THREE.Mesh
    Bulb_E002_M_BulbFilament_0: THREE.Mesh
  }
  materials: {
    M_BulbGlass: THREE.MeshStandardMaterial
    M_BulbHolder: THREE.MeshStandardMaterial
    M_BulbFilament: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bulbs.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[108.225, -28.44, 105.828]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_B004_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_B004_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_B004_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[200.761, 3.019, 118.742]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_A004_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_A004_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_A004_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[15.327, -43.309, 118.231]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_C003_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_C003_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_C003_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-76.483, 144.976, 119.163]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_D005_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_D005_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_D005_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-159.396, 114.589, 74.943]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_E005_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_E005_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_E005_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[63.331, 25.634, -35.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_B001_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_B001_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_B001_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[154.04, -142.573, 28.032]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_A001_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_A001_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_A001_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-33.763, 6.313, -1.657]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_C001_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_C001_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_C001_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-121.812, -5.809, 4.281]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_D001_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_D001_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_D001_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-201.099, -44.957, -5.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_E001_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_E001_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_E001_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[103.791, -17.403, -92.01]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_B002_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_B002_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_B002_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[192.687, 128.283, -87.671]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_A002_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_A002_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_A002_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[9.1, -9.362, -133.211]} rotation={[Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_C002_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_C002_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_C002_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-93.328, 12.398, -87.254]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_D002_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_D002_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_D002_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
        <group position={[-161.382, -143.36, -125.956]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bulb_E002_M_BulbGlass_0.geometry} material={materials.M_BulbGlass} />
          <mesh geometry={nodes.Bulb_E002_M_BulbHolder_0.geometry} material={materials.M_BulbHolder} />
          <mesh geometry={nodes.Bulb_E002_M_BulbFilament_0.geometry} material={materials.M_BulbFilament} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bulbs.glb')
